services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    command: >
      sh -c "if [ ! -f .env ]; then
        echo 'No .env found - copying from .env.example...';
        cp .env.example .env;
        echo 'Generating APP_KEY...';
        php artisan key:generate;
      fi &&
      php artisan migrate --force &&
      php artisan products:import &&
      php artisan serve --host=0.0.0.0 --port=8000"

  frontend:
    image: node:24
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    command: >
      sh -c "npm ci || npm install && npm run dev -- --host 0.0.0.0 --port 5173"